# Generated by Django 4.2.3 on 2023-08-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0004_alter_car_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="car_photo",
            field=models.ImageField(upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_1",
            field=models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_2",
            field=models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="car",
            name="car_photo_3",
            field=models.ImageField(blank=True, upload_to="photos/%Y/%m/%d/"),
        ),
    ]
